name: provider_devtools_extension
description: "The Flutter web app for the package:riverpod DevTools extension."
publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  collection: ^1.15.0
  devtools_extensions: ^0.0.10
  devtools_app_shared: ^0.0.4
  # Pinning to a specific version of riverpod, to ensure that
  # the extension is using the same contract version.
  hooks_riverpod: 3.0.0-dev.3
  flutter_riverpod: 3.0.0-dev.3
  riverpod: 3.0.0-dev.3
  logging: ^1.1.1
  vm_service: ^13.0.0
  riverpod_annotation: ^0.14.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_driver:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  build_runner: ^2.4.7
  riverpod_generator:
  freezed: ^2.4.5

flutter:
  uses-material-design: true
